version: '3.8'

services:
  # frontend
  web:
    build: ./services/frontend
    container_name: frontend
    command: npm run serve
    ports:
    - "8080:8080"

  #backend
  api:
    build: ./services/backend
    container_name: backend
    command: "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
    - "8000:8000"
    depends_on:
    - postgre

  # db
  postgre:
    image: postgres
    container_name: postgreSQL
    ports:
    - "5432:5432"
    environment:
      POSTGRE_DB: postgres
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pwd
    