version: '3.8'

services:
  # frontend
  web:
    build: ./services/frontend
    container_name: frontend
    command: npm run serve
    ports:
    - "8080:8080"

  #backend
  api:
    build: ./services/backend
    container_name: backend
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0"]
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
    - "8000:8000"
    depends_on:
      - postgres

  # db
  postgres:
    container_name: postgres
    image: postgres:14.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"