version: '3.8'

services:
  # frontend
  frontend:
    build: ./services/frontend
    container_name: frontend
    command: npm run serve
    ports:
    - "8080:8080"
    depends_on: 
      backend:
        condition: service_started
      kong:
        condition: service_healthy
    # restart: always
    networks:
      - default

  #backend
  backend:
    build: ./services/backend
    container_name: backend
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8005"]
    environment:
      BACKEND_USER: ${BACKEND_USER}
      BACKEND_PASSWORD: ${BACKEND_PASSWORD}
      BACKEND_DB: ${BACKEND_DB}
    ports:
      - "8005:8005"
    depends_on:
      postgres:
        condition: service_healthy
    # restart: always
    networks:
      - default

  # db
  postgres:
    container_name: postgres
    image: postgres:14.0
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./services/backend/postgres-data:/var/lib/postgresql/data
      - ./services/backend/db_init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 15
    # restart: always
    networks:
      - default

  # gpt-2
  gpt2:
    build: ./services/gpt-2
    container_name: gpt2
    command: "python3 auto_generate_texts.py"
    environment:
      BACKEND_USER: ${BACKEND_USER}
      BACKEND_PASSWORD: ${BACKEND_PASSWORD}
      BACKEND_DB: ${BACKEND_DB}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - default

  kong:
    build: ./services/kong
    container_name: kong
    networks:
      - default
    environment:
      KONG_DATABASE: ${KONG_DATABASE}
      KONG_DECLARATIVE_CONFIG: ${KONG_DECLARATIVE_CONFIG}
      KONG_CLIENT_KEY: ${KONG_CLIENT_KEY}
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 15
    depends_on:
      keycloak:
        condition: service_healthy
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "8443:8443/tcp"
      - "8444:8444/tcp"

  keycloak:
    image: jboss/keycloak:15.0.1
    container_name: keycloak
    networks:
      - default
    ports:
      - "8085:8080"
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/auth/realms/master"]
      interval: 10s
      timeout: 5s
      retries: 15
    depends_on:
      postgres:
        condition: service_healthy