CREATE DATABASE backend;
CREATE DATABASE kong;

CREATE USER kong WITH PASSWORD 'kong';
CREATE USER usr_backend WITH PASSWORD 'pwd_backend';

GRANT ALL PRIVILEGES ON DATABASE backend TO usr_backend;
GRANT ALL PRIVILEGES ON DATABASE kong TO kong;
